### ISSUE TITLE
reload not working

### ISSUE THREAD

**Issue by ragmel** [RobWin/supervisorclusterctl#1]
Hi,
Whenever I do a

supervisorclusterctl myremotehost reload

I get 

Traceback (most recent call last):
  File "/usr/local/bin/supervisorclusterctl", line 9, in <module>
    load_entry_point('supervisorclusterctl==0.1.1', 'console_scripts', 'supervisorclusterctl')()
  File "/usr/local/lib/python2.7/dist-packages/supervisorclusterctl/supervisorclusterctl.py", line 63, in main
    supervisorctl_argument = getattr(args, "process-name")
AttributeError: 'Namespace' object has no attribute 'process-name'

It's expecting a process-name, which shouldn't. I looked at the code and couldn't see a proper option to handle the reload.

I'm using Mint 17.1, and python 2.7.6.

Thanks

**Comment by RobWin** [comment]
Weee. First visible user of supervisorclusterctl  :)
I will have a look at it. 
Thx.

**Comment by RobWin** [comment]
@cragusa Indeed. `reload` is missing in line 62.

**Comment by ragmel** [comment]
Cool, I'll wait for a fix then. Thanks

**Comment by RobWin** [comment]
Please retest.
Version 0.1.2 is public.

**Comment by ragmel** [comment]
tested, seems to fine, thanks!

On the other hand, is it possible to have an option to start remote supervisord?

**Comment by RobWin** [comment]
You want to start the supervisord service on remote systems?
I guess, it depends on init system of the linux OS. Since there are so many different init systems, it is not in the scope of this project.

**Comment by ragmel** [comment]
I wasn't thinking in terms of init, but more in terms of ansible,

---
- hosts: remotenodes
  tasks:
  - name: starting remote supervisor
    command: supervisord

so having a load option would just kick something like that. It was just an idea, it can be done with ansible anyway. Thanks
